# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
GET 127.0.0.1:8000/mail/test?email=2440784496@qq.com

###
GET 127.0.0.1:8000/auth/code?email=2440784496@qq.com


###
POST 127.0.0.1:8000/auth/register
Content-Type: application/json

{
  "email": "2440784496@qq.com",
  "username": "zyl",
  "password": "111111",
  "confirm_password": "111111",
  "code": "6105"
}


###
POST 127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "email": "2440784496@qq.com",
  "password": "111111"
}

###
POST 127.0.0.1:8000/name
Content-Type: application/json

{
  "surname": "张",
  "length": "两字",
  "gender": "男",
  "other": "不要网红名称"
}


